### ISSUE TITLE
Stacked bar: Zero/nullish values result "y=NaN%" for proceeding elements

### ISSUE THREAD

**Issue by brodysmith1** [stephenhutchings/shown#1]
The issue is caused by `utils.sum()`

`v` may have a valid, but falsy, `value` property, but this is not handled correctly in the current form.

`const sum = (array) => array.reduce((m, v) => m + (v.value || v), 0)`

Should be replaced by:

`const sum = (array) => array.reduce((m, v) => m + (v.value !== undefined ? v.value : v), 0)`

**Comment by stephenhutchings** [comment]
Thanks @brodysmith1. Fixed in v0.2.1.
