### ISSUE TITLE
Examples don't work out of the box because of missing styles

### ISSUE THREAD

**Issue by gwn** [stephenhutchings/shown#2]
Somewhere in the documentation, an instruction to include the [stylesheet](https://github.com/stephenhutchings/shown/blob/master/src/css/shown.css) into the source code needs to be added.

Unless it is done, people might believe that the library is broken.

**Comment by stephenhutchings** [comment]
Thanks for raising this issue. I've added a short note at the top of the docs which hopefully makes this clearer.
